### PR TITLE
use Gatsby theme

### PR DESCRIPTION
**Pull request by victoriabernard92**
This PR migrates us to use gatsy themes.
- allows theme to pass in option for path (e.g. `workers`)
- separate all gatsby logic into it's own dir, with exception of  template logic
- go from npm to yarn so we can take advantage of yarn workspaces for CI
- make all exported components use ES6 modules

Poke around at staging.bigfluffycloudflare.com/workers

### CODE REVIEW

**Comment by signalnerve** [comment]
SO AWESOME

**Comment by signalnerve** [comment]
is this ready for review? i'll pull it down and run it locally when it is

**Comment by ispivey** [comment]
This is a big PR, and hard to meaningfully review at the moment! A few things would help:

1. Can you address conflicts?
2. Can you update the PR description to describe the changes in more detail? A bulleted list of meaningful changes, and why they're being made, would help us review.
3. Can you go through the "Changes" view yourself, from the perspective of a reviewer? If you see changes that would be confusing to a reviewer, please leave a note explaining the change. If you see a change that is unrelated to the Gatsby themes migration, consider removing it and including it in a separate PR.

Thank you!

**Comment by signalnerve** [comment]
looks good to me in staging. i agree it's hard to review but i'm familiar with themes generally and there weren't any surprises when i opened this pr up. happy to defer to victoria on how she feels about merging this stuff

**Comment by ispivey** [comment]
@victoriabernard92 this caused a regression where we no longer have the Workers branding or nav-bar on https://developers.cloudflare.com/workers/ . 

Can you revert?

**Pull request merged**
