### PR TITLE
Change toml syntax highlighting

### PR DESCRIPTION
**Pull request by victoriabernard92**
fixes https://github.com/cloudflare/workers-docs/issues/430

Note the first bullet on that issue was fixed in commit 8c1ea189cea5e835366d7c26d83718deca46ab8d

### CODE REVIEW

**Comment by EverlastingBugstopper** [comment]
do you have screenshots of before and after? not sure why we would want to eliminate toml styling - maybe we just want to change the css in hugo instead of removing entirely?

**Comment by ashleymichal** [comment]
> do you have screenshots of before and after? not sure why we would want to eliminate toml styling - maybe we just want to change the css in hugo instead of removing entirely?

+1

**Comment by signalnerve** [comment]
I have the same question as the above two comments!

**Comment by victoriabernard92** [comment]
Since very close to moving to gatsby I am actually going to close this PR! We can fix this in React

**Pull request closed without merging**
