### PR TITLE
KV limit to 10MB

### PR DESCRIPTION
**Pull request by adaptive**
Noticed this raise on the dashboard, tested and is valid, but not documented.
cc @steveklabnik 

Screen Shot 2019-10-25 at 1 38 57 AM

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hehe, you're fast. we did roll this out but haven't made it public yet; that doesn't mean i'm not opposed to updating these docs. we'll have some more work to do that this would have been a part of

**Comment by signalnerve** [comment]
@steveklabnik did you want to get this reviewed and merged, or is there another PR we're going to make with this and other KV changes?

**Comment by signalnerve** [comment]
@adaptive can you resolve the merge conflict here?

**Comment by adaptive** [comment]
@signalnerve conflict fixed.

**Comment by steveklabnik** [comment]
@signalnerve this is good to go, but I don't have merge perms, please have at it :)

**Pull request merged**
