### PR TITLE
Free KV expirations

### LINKED ISSUE #234: KV docs don't compare deletes vs expiry
deletes cost money, expiring keys do not. this should be fixed

### PR DESCRIPTION
**Pull request by adaptive**
as per @steveklabnik #234 
I believe "Unlimited Worker KV automatic expirations" is a safe phrasing approach.
Since writing permanent and expiring keys costs the same, and only the automatic eviction is free.
 
fixes #234

### CODE REVIEW

**Comment by steveklabnik** [comment]
I think there's an interesting thing at play here; that is, do we say on the "what we charge for" page something that's free? I can see it both ways.

**Comment by victoriabernard92** [comment]
Waiting on @steveklabnik approval on this one since I am out of context

**Comment by a-robinson** [comment]
Like @steveklabnik, I wouldn't naturally include something like this in the pricing docs, but he can make the call. So consider this a ping, @steveklabnik :)

**Comment by adaptive** [comment]
@a-robinson @steveklabnik do you suggest something like?
> "Free Worker KV automatic expirations"

**Comment by steveklabnik** [comment]
Hey @adaptive , I was out sick for a bit, but I'm back now!

How about something like this: instead of calling this out specifically, we add a sentence after the list that says something like "Usage of all other features of KV do not affect pricing", or something like that? Part of the reason why it's awkward to enumerate negatives like this is that you miss some, and that makes people wonder. For example, if we accepted this PR as-is, one may ask, "are there other features that aren't listed here that are free or paid?"

**Comment by victoriabernard92** [comment]
@adaptive Checking in, did you see Steve's comment? Are you willing to make that change in the wording?

**Comment by adaptive** [comment]
Sorry, I missed @steveklabnik comment.

@victoriabernard92 I changed to @steveklabnik suggestion.

**Pull request merged**
