### PR TITLE
Minor spelling fixes

### PR DESCRIPTION
**Pull request by nagpai**
Fix spelling of WordPress (Capitalize P)

### CODE REVIEW

**Comment by victoriabernard92** [comment]
This looks good to me, just fix the merge conflicts. Sorry for the delay was managing the gatsby rewrite and wanted to make sure these changes didn't get lost @nagpai

**Comment by nagpai** [comment]
> This looks good to me, just fix the merge conflicts. Sorry for the delay was managing the gatsby rewrite and wanted to make sure these changes didn't get lost @nagpai

Thank you @victoriabernard92  . I am a relatively new user of GH. It looks like resolving the merge conflict would require someone with write access to the repo. (the resolve button appears grey to me)

**Comment by signalnerve** [comment]
@nagpai sorry to ask this, but due to the number of changes in the repo over the next couple days, github won't actually let me resolve these conflicts! if you could open a new PR based off of master, it should be easily reviewable/mergeable. thanks!

**Comment by nagpai** [comment]
Closing the PR here in favor of 
https://github.com/cloudflare/workers-docs/pull/686

cc @signalnerve  - did i do this right?

**Pull request closed without merging**
