### PR TITLE
KV Bulk write clarification

### PR DESCRIPTION
**Pull request by adaptive**
Adding the limits of KV Bulk write.

### CODE REVIEW

**Comment by victoriabernard92** [comment]
@adaptive Would you mind fixing the merge conflicts and then it looks good to merge. Thank you, you're awesome :D

**Comment by adaptive** [comment]
@victoriabernard92 as soon the master repo is in par with the docs site, just need to see the new positioning.

**Comment by victoriabernard92** [comment]
@adaptive are you still able to fix the conflicts here?

**Comment by adaptive** [comment]
@victoriabernard92 just repositioned the phrase

**Pull request merged**
