### PR TITLE
Github links to template pages

### LINKED ISSUE #211: Add github icon to templates
Match  @neynah's design for the template gallery by including a github icon next to source code links
https://www.figma.com/file/S52Y2mOVub2ZWqNkzJz4ak/Template-Gallery-%2B-Pages-(Draft)

image

SVG:
```<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
  <path d="M8,.859A7.208,7.208,0,0,0,5.721,14.9c.36.063.5-.153.5-.342,0-.171-.009-.739-.009-1.342-1.811.333-2.279-.441-2.424-.847a2.621,2.621,0,0,0-.739-1.018c-.252-.135-.613-.468-.009-.478a1.442,1.442,0,0,1,1.108.739,1.541,1.541,0,0,0,2.1.595,1.516,1.516,0,0,1,.459-.964c-1.6-.18-3.279-.8-3.279-3.559a2.805,2.805,0,0,1,.739-1.937,2.59,2.59,0,0,1,.072-1.91s.6-.189,1.982.739a6.8,6.8,0,0,1,3.6,0C11.2,3.643,11.8,3.841,11.8,3.841a2.59,2.59,0,0,1,.072,1.91,2.789,2.789,0,0,1,.739,1.937c0,2.766-1.685,3.379-3.288,3.559a1.707,1.707,0,0,1,.487,1.333c0,.964-.009,1.739-.009,1.982,0,.189.135.414.5.342A7.211,7.211,0,0,0,8,.859Z"/>
</svg>
```

### PR DESCRIPTION
**Pull request by victoriabernard92**
image
And for snippets points to the registry:
image

fixes #211

### CODE REVIEW

**Comment by signalnerve** [comment]
design questions for the github links in the screenshots, maybe worth getting @neynah's take too:



should the "last updated" text be aligned with the repo name? i noticed that it's positioned between the icon and repo name at the moment

---



i noticed that the text seems to be line-wrapping and overflowing. is it possible to keep it at a single line and overflow it? should the last updated subtitle text also be included in this too?

**Comment by victoriabernard92** [comment]
Responding to @signalnerve 
- **text wrapping**
Some of the repos will evitably have really long names, so I think ellipsing them is best. 

-  **missing "last updated"**
Snippets don't have updated at because it requires the github api which rate limits for all the templates on that repo, will consider fixing later if it's a feature people love. the last updated field is more valuable for boilerplates over snippets

-  **"last updated" text be aligned with the repo name**
her original design actually had this aligning right. Note version tag is not possible or relevant here. Open to changing it. Her design from figma:
image

**Comment by donjo** [comment]
Jumping in since @neynah is out on vacation. 

For the alignment thing I would say align the `Last updated:` with where the version information would be since we don't have that info

Screen Shot 2019-11-21 at 1 31 34 PM

And for the line-wrapping, even with `white-space: nowrap` there is some room in the parent container for things to grow off to the right. Here's an example of some extra junk added to make it a really long string. 

Screen Shot 2019-11-21 at 1 50 35 PM

So I would recommend that unless we want to mess with the line height and icon alignment of that wrapping

**Comment by signalnerve** [comment]
thanks @donjo! also, welcome :) 

i agree on the alignment. @victoriabernard92 can you open another PR with a fix for that?

for the line-wrapping, i messed around with it a bit locally but couldn't get a perfect fix. to be clear, the ellipsis overflow is 👍, it's the line-wrapping that i think is a little wonky. IMO the right styling would be `template-registry/conditional...` – the ellipses would start sooner and the text would stay as a single line, without the line-wrapping messing up the center alignment.

as an alternate idea, is it possible that if the repo title is too long, we can fallback to "View on GitHub" as the text?

**Pull request merged**
